//! Generate the mandatory RW-publication admission policy from the SAME typed
//! specs the controller verifies before creating a compatibility Job.

use anyhow::Result;
use kopiur_api::rw_publication_admission::{binding, policy};

use crate::artifact::Artifact;

const HEADER: &str = "# GENERATED by `cargo xtask gen-admission` — DO NOT EDIT\n";

/// Raw install bundle and opt-in Helm template, covered by `gen-all --check`.
pub fn artifacts() -> Result<Vec<Artifact>> {
    let body = format!(
        "{}---\n{}",
        serde_yaml::to_string(&policy())?,
        serde_yaml::to_string(&binding())?,
    );
    Ok(vec![
        Artifact::new(
            "admission/rw-publication.yaml".into(),
            format!("{HEADER}{body}"),
        ),
        Artifact::new(
            "helm/kopiur/templates/rw-publication-admission.tpl".into(),
            format!(
                "{HEADER}{{{{- if .Values.rwPublicationAdmission.enabled }}}}\n{body}{{{{- end }}}}\n"
            ),
        ),
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn raw_and_helm_emit_identical_mandatory_policy_specs() {
        let artifacts = artifacts().unwrap();
        assert_eq!(artifacts.len(), 2);
        let raw = artifacts[0].content.strip_prefix(HEADER).unwrap();
        let helm = artifacts[1].content.strip_prefix(HEADER).unwrap();
        assert_eq!(
            helm,
            format!("{{{{- if .Values.rwPublicationAdmission.enabled }}}}\n{raw}{{{{- end }}}}\n")
        );
    }
}
